services:
  postgres:
    image: postgres:18-alpine
    container_name: film-postgres
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql
      - ./backend/sql/init.sql:/docker-entrypoint-initdb.d/01-init.sql
      - ./backend/sql/data.sql:/docker-entrypoint-initdb.d/02-data.sql
    networks:
      - film-network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: film-pgadmin
    restart: unless-stopped
    env_file:
      - .env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - film-network
    depends_on:
      postgres:
        condition: service_healthy

  backend:
    build: ./backend
    container_name: film-backend
    restart: unless-stopped
    env_file:
      - ./backend/.env
    ports:  
      - "3000:3000"
    networks:
      - film-network
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      disable: true

  frontend:
    build: ./frontend
    container_name: film-frontend
    restart: unless-stopped
    networks:
      - film-network
    healthcheck:
      disable: true

  nginx:
    build: ./nginx
    container_name: film-nginx
    ports:
      - "80:80"
    restart: unless-stopped
    networks:
      - film-network
    depends_on:
      frontend:
        condition: service_started
      backend:
        condition: service_started
    healthcheck:
      disable: true

networks:
  film-network:
    driver: bridge
    name: film-network

volumes:
  postgres_data:
    name: film-postgres-data
  pgadmin_data:
    name: film-pgadmin-data
